// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package expressions

type Expression struct {
	ID       string
	Expr     string
	Res      float64
	Finished bool
	Error    bool
}
