basePath: /api/v1
definitions:
  dto.ApiError:
    properties:
      code:
        example: 500
        type: integer
      message:
        example: 'error: nil ptr dereference'
        type: string
    type: object
  dto.AuthRequest:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  dto.AuthResponse:
    properties:
      token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDY2OTE0MjQsImlhdCI6MTc0NjYwNTAyNCwic3ViIjoiMDFKVEU1VE5URVZZREVQUzhHRUUwWUc0Qk0ifQ.yDYZBaEAgeAshF7zLSGNxVL8Q5P70YheQCXO68pEzHc
        type: string
    type: object
  dto.CalculateRequest:
    properties:
      expression:
        example: 2+2
        type: string
    type: object
  dto.CalculateResponse:
    properties:
      id:
        example: 01JTE60CDWQ5R3QSWZBP8J6FG3
        type: string
    type: object
  dto.Expression:
    properties:
      expression:
        example: 2+2
        type: string
      id:
        example: 01JTE60CDWQ5R3QSWZBP8J6FG3
        type: string
      result:
        example: 4
        type: number
      status:
        example: DONE
        type: string
    type: object
  dto.GetByIdExpressionResponse:
    properties:
      expression:
        $ref: '#/definitions/dto.Expression'
    type: object
  dto.ListAllExpressionsResponse:
    properties:
      expressions:
        items:
          $ref: '#/definitions/dto.Expression'
        type: array
    type: object
host: localhost:8080
info:
  contact: {}
  description: Yandex Lyceum Calculator API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Orchestrator API
  version: "1.0"
paths:
  /calculate:
    post:
      consumes:
      - application/json
      description: Добавить математическое выражение из чисел, знаков [+, -, *, /,
        (, )] в очередь на выполнение. Возвращает ULID ID при успешном запросе
      parameters:
      - description: Объект, содержащий в себе выражение
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.CalculateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CalculateResponse'
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.CalculateResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ApiError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/dto.ApiError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/dto.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ApiError'
      security:
      - Bearer: []
      tags:
      - calculate
  /expressions:
    get:
      consumes:
      - application/json
      description: Выражение состоит из ID (ULID), Result (0 или другое число) и Status
        (DONE - Успешно выполнено, FAILED - Ошибка при выполнении, PROCESSING - Выполняется).
        Возвращает список выражений при успешном запросе
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ListAllExpressionsResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/dto.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ApiError'
      security:
      - Bearer: []
      tags:
      - expressions
  /expressions/{id}:
    get:
      consumes:
      - application/json
      description: Выражение состоит из ID (ULID), Result (0 или другое число) и Status
        (DONE - Успешно выполнено, FAILED - Ошибка при выполнении, PROCESSING - Выполняется).
        Возвращает выражение при успешном запросе
      parameters:
      - description: 01JTE60CDWQ5R3QSWZBP8J6FG3
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetByIdExpressionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ApiError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/dto.ApiError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ApiError'
      security:
      - Bearer: []
      tags:
      - expressions
  /login:
    post:
      consumes:
      - application/json
      description: Войти в аккаунт с помощью логина и пароля. Возвращает JWT API Token
        при успешном запросе
      parameters:
      - description: Данные для входа
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.AuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ApiError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ApiError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ApiError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/dto.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ApiError'
      summary: Войти в аккаунт
      tags:
      - auth
  /register:
    post:
      consumes:
      - application/json
      description: Создать новый аккаунт с помощью логина и пароля. Возвращает JWT
        API Token при успешном запросе
      parameters:
      - description: Данные для регистрации
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.AuthRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ApiError'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/dto.ApiError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/dto.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ApiError'
      summary: Зарегистрировать новый аккаунт
      tags:
      - auth
securityDefinitions:
  Bearer:
    description: '"Введите ''Bearer TOKEN'' чтобы правильно использовать JWT API Token"'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
