name: build
on:
  push:
    paths-ignore:
      - .gitignore
      - README.md
      - compose.yml
      - .env
  pull_request:

permissions:
  contents: read
  pull-requests: write

env:
  GITHUB_CI: "1"

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        include:
          - dir: agent
          - dir: orchestrator

    name: build (${{ matrix.dir }})
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.dir }}

    steps:
      - name: Convert repository to lowercase
        id: lowercase
        run: |
          lowercase_repo=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "repository=$lowercase_repo" >> $GITHUB_OUTPUT

      - name: Copy repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: linuxfight
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
          working-directory: ${{ matrix.dir }}

      - name: Run tests
        run: go test -v ./...

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.lowercase.outputs.repository }}-${{ matrix.dir }}
          tags: |
            type=ref,event=branch
            type=sha

      - name: Build docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.dir }}
          push: true
          platforms: linux/arm64,linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ steps.lowercase.outputs.repository }}-${{ matrix.dir }}:buildcache
          cache-to: type=registry,ref=${{ steps.lowercase.outputs.repository }}-${{ matrix.dir }}:buildcache,mode=max
